// COPYRIGHT (C) HARRY CLARK 2025
// HITACHI SH4 FPU EMULATOR WITH SH2 FP SUPPORT

// THIS FILE PERTAINS TOWARDS BASIC TYPES OF THE CPU WITHOUT HAVING TO NECESSARILY 
// EMULATE THE ENTIRE MICROPROCESSER, ENOUGH TO GET THE FPU WORKING

// NESTED INCLUDES

#include "sh.h"
#include "sh_types.h"

static uint32_t REG_M;
static uint32_t REG_N;

// FLOATING POINT ADD FROM FLOATING REGISTER M TO N BASED OFF THE RESULT OF THE PROCEDURE REGISTER (RTS)

void FADD(const uint16_t OPCODE)
{
    REG_M = SH_REG_M(OPCODE);
    REG_N = SH_REG_N(OPCODE);

    if(SH_BASE_T->FPU_RTS)
    {
        REG_N = REG_N & 14;
        REG_M = REG_M & 14;

        SH_FP_RD(REG_N) = SH_FP_RD(REG_N) + SH_FP_RS(REG_M);
    }

    else
    {
        SH_FP_RS(REG_N) = SH_FP_RS(REG_N) + SH_FP_RS(REG_M);
    }
}